/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as PacksRouteImport } from './routes/packs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIdEditRouteImport } from './routes/templates.$id.edit'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksRoute = PacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIdEditRoute = TemplatesIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => TemplatesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/packs': typeof PacksRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/templates/$id/edit': typeof TemplatesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/packs': typeof PacksRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/templates/$id/edit': typeof TemplatesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/packs': typeof PacksRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/templates/$id/edit': typeof TemplatesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/packs' | '/templates' | '/templates/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/packs' | '/templates' | '/templates/$id/edit'
  id: '__root__' | '/' | '/packs' | '/templates' | '/templates/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PacksRoute: typeof PacksRoute
  TemplatesRoute: typeof TemplatesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs': {
      id: '/packs'
      path: '/packs'
      fullPath: '/packs'
      preLoaderRoute: typeof PacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$id/edit': {
      id: '/templates/$id/edit'
      path: '/$id/edit'
      fullPath: '/templates/$id/edit'
      preLoaderRoute: typeof TemplatesIdEditRouteImport
      parentRoute: typeof TemplatesRoute
    }
  }
}

interface TemplatesRouteChildren {
  TemplatesIdEditRoute: typeof TemplatesIdEditRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesIdEditRoute: TemplatesIdEditRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PacksRoute: PacksRoute,
  TemplatesRoute: TemplatesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
