/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PacksRouteImport } from './routes/packs'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as DesignsRouteImport } from './routes/designs'
import { Route as DataRouteImport } from './routes/data'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIdEditRouteImport } from './routes/templates.$id.edit'
import { Route as DesignsIdEditRouteImport } from './routes/designs.$id.edit'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksRoute = PacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignsRoute = DesignsRouteImport.update({
  id: '/designs',
  path: '/designs',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIdEditRoute = TemplatesIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => TemplatesRoute,
} as any)
const DesignsIdEditRoute = DesignsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => DesignsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data': typeof DataRoute
  '/designs': typeof DesignsRouteWithChildren
  '/generate': typeof GenerateRoute
  '/history': typeof HistoryRoute
  '/packs': typeof PacksRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/designs/$id/edit': typeof DesignsIdEditRoute
  '/templates/$id/edit': typeof TemplatesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data': typeof DataRoute
  '/designs': typeof DesignsRouteWithChildren
  '/generate': typeof GenerateRoute
  '/history': typeof HistoryRoute
  '/packs': typeof PacksRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/designs/$id/edit': typeof DesignsIdEditRoute
  '/templates/$id/edit': typeof TemplatesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data': typeof DataRoute
  '/designs': typeof DesignsRouteWithChildren
  '/generate': typeof GenerateRoute
  '/history': typeof HistoryRoute
  '/packs': typeof PacksRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/designs/$id/edit': typeof DesignsIdEditRoute
  '/templates/$id/edit': typeof TemplatesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data'
    | '/designs'
    | '/generate'
    | '/history'
    | '/packs'
    | '/settings'
    | '/templates'
    | '/designs/$id/edit'
    | '/templates/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data'
    | '/designs'
    | '/generate'
    | '/history'
    | '/packs'
    | '/settings'
    | '/templates'
    | '/designs/$id/edit'
    | '/templates/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/data'
    | '/designs'
    | '/generate'
    | '/history'
    | '/packs'
    | '/settings'
    | '/templates'
    | '/designs/$id/edit'
    | '/templates/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataRoute: typeof DataRoute
  DesignsRoute: typeof DesignsRouteWithChildren
  GenerateRoute: typeof GenerateRoute
  HistoryRoute: typeof HistoryRoute
  PacksRoute: typeof PacksRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs': {
      id: '/packs'
      path: '/packs'
      fullPath: '/packs'
      preLoaderRoute: typeof PacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designs': {
      id: '/designs'
      path: '/designs'
      fullPath: '/designs'
      preLoaderRoute: typeof DesignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$id/edit': {
      id: '/templates/$id/edit'
      path: '/$id/edit'
      fullPath: '/templates/$id/edit'
      preLoaderRoute: typeof TemplatesIdEditRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/designs/$id/edit': {
      id: '/designs/$id/edit'
      path: '/$id/edit'
      fullPath: '/designs/$id/edit'
      preLoaderRoute: typeof DesignsIdEditRouteImport
      parentRoute: typeof DesignsRoute
    }
  }
}

interface DesignsRouteChildren {
  DesignsIdEditRoute: typeof DesignsIdEditRoute
}

const DesignsRouteChildren: DesignsRouteChildren = {
  DesignsIdEditRoute: DesignsIdEditRoute,
}

const DesignsRouteWithChildren =
  DesignsRoute._addFileChildren(DesignsRouteChildren)

interface TemplatesRouteChildren {
  TemplatesIdEditRoute: typeof TemplatesIdEditRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesIdEditRoute: TemplatesIdEditRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataRoute: DataRoute,
  DesignsRoute: DesignsRouteWithChildren,
  GenerateRoute: GenerateRoute,
  HistoryRoute: HistoryRoute,
  PacksRoute: PacksRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
